# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit report-template.Rmd to modify this file

## ----MDS-Figure, fig.width=5, echo=TRUE, eval=TRUE----------------------------
library(png)
library(grid)
img <- readPNG("images/mds.png")
grid.raster(img)

